language: php

php:
  - 7.1

branches:
  except:
    - /^analysis-/

before_script:
  - travis_retry composer self-update
  - composer install
  - nvm install latest
  - npm install -g yarn
  - yarn
  - yarn run dev

script:
 - phpunit
