language: php

php:
  - 7.1

branches:
  except:
    - /^analysis-/

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer install --prefer-dist --ignore-platform-reqs
  - nvm install node
  - npm install -g yarn
  - yarn
  - npm run dev -- --progress=false

script:
 - ./vendor/bin/phpunit
