language: php

php:
  - 7.1

branches:
  except:
    - /^analysis-/

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache/files

env:
  - APP_ENV=testing

before_script:
  - travis_retry composer self-update
  - composer install --prefer-dist
  - nvm install node
  - npm install -g yarn
  - yarn
  - yarn run dev

script:
 - ./vendor/bin/phpunit
